# Generated by Django 3.2.4 on 2021-06-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgame', '0002_auto_20210609_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
