# Generated by Django 3.2.4 on 2021-06-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgame', '0003_auto_20210609_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('nivel_educacional', models.CharField(max_length=50)),
            ],
        ),
    ]
