# Generated by Django 3.2.4 on 2021-06-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgame', '0004_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
