# Generated by Django 3.2.4 on 2021-06-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgame', '0006_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEducacional',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamburgame.pais', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_educacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamburgame.niveleducacional', verbose_name='NivelEducacional'),
        ),
    ]
